name: sentiment-analysis
channels:
  - defaults
dependencies:
  - python=3.12.5
  - pip
  - huggingface_hub
  - matplotlib
  - numpy
  - transformers
  - requests
  - beautifulsoup4
  - pandas
  - lxml
  - pytest
